image:
- Visual Studio 2022
- macOS

skip_branch_with_pr: true
stack: python 3.12

platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: VjOQklE3JTnCsB0zT8gIgfOaYFVN9s+jXeWQzAXJbtLfQn6HGBl5zOoq3dbyn0qP4wDZwC0OhWlQgGznj0EoQEJ5s17i8GxV7Lhq9PqSv2uFGsOijbJXSd6sJRPubaoq

install:
- pip install -U setuptools wheel
- pip install -g uv

build_script:
- flet pack src/main.py --name pochi-mat --product-name pochi-mat --product-version "0.0.1"
# - flet pack src/main.py --name pochi-mat --icon icon.png --product-name pochi-mat --product-version "1.2.3" --copyright "Copyright (c) 2022"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
-
  matrix:
    only:
    - image: Visual Studio 2022

  before_build:
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
    - uv sync

  after_build:
  - 7z a pochi-mat-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: pochi-mat-windows.zip

#
#   macOS package
#
-
  matrix:
    only:
    - image: macOS

  before_build:
    - uv sync

  after_build:
  - tar -czvf pochi-mat-macos.tar.gz -C dist pochi-mat.app

  artifacts:
  - path: pochi-mat-macos.tar.gz
