version: "3"

tasks:
  gen_requirements:
    cmd: uv pip compile pyproject.toml > requirements.txt

  full_mac_build:
    cmd: uv run pyinstaller src/main.py --onedir --collect-all "ja_ginza" --collect-all "ginza" --collect-all "spacy" --collect-all "spacy_legacy" --add-data "src/assets/pochi-mat.icns:." -i=pochi-mat.icns --name=pochi-mas[mac]

  mac_build:
    cmd: uv run pyinstaller pochi-mas[mac].spec

  full_win_build:
    cmd: uv run pyinstaller .\src\main.py --onedir --collect-all "ja_ginza"  --collect-all "ginza" --collect-all "spacy"  --collect-all "spacy_legacy" --hidden-import "ja_ginza" --hidden-import "ginza" --name pochi-mat[win] --add-data "src/assets/pochi-mat.ico:." -i src/assets/pochi-mat.ico

  win_build:
    cmd: uv run pyinstaller pochi-mas[win].spec

  check:all:
    - task: format
    - task: ruff
    - task: pyright
    - task: test

  test:
    cmd: uv run pytest

  pyright:
    cmd: uv run pyright

  format:
    cmd: uv run ruff format --check .

  ruff:
    cmd: uv run ruff check .
